### ISSUE TITLE
Duplicate True Crime by Monkey Mind Games and Pugnacious Games

### ISSUE THREAD

**Issue by johnhelmuth** [fate-srd/fate-product-list#19]
The DrivethruRPG URL in both rows uses the same product id:

    229: Monkey Mind Games,True Crime,https://www.drivethrurpg.com/en/product/315482?affiliate_id=144937
    ...
    238: Pugnacious Games,True Crime,https://www.drivethrurpg.com/product/315482/True-Crime?affiliate_id=144937

DrivethruRPG lists the publisher as Monkey Mind Games.

We need to delete  line 238, I think.

**Comment by amazingrando** [comment]
Agreed. Remove line 238.

**Comment by johnhelmuth** [comment]
There will probably be a slew of PRs this weekend.

**Comment by amazingrando** [comment]
Awesome!

**Comment by johnhelmuth** [comment]
Verified that there are not two True Crime games listed on the product page from 2 different publishers, only Monkey Mind Games is listed.
