### ISSUE TITLE
CSV sorting

### ISSUE THREAD

**Issue by szabba** [fate-srd/fate-product-list#9]
Do we want to keep the CSV sorted? My intuition is "yes, first by publisher then by product" but that opens the can of worms of maintaining the ordering.

(First mentioned under #3.)

**Comment by johnhelmuth** [comment]
I don't know enough about how the data gets from the CSV to the page.

When it was in the database, the order of rows could easily be specified at the time the page was rendered.

Depending on the tooling that is selected to add this file into the build process, that may still be the best place to do it.

I'll wait for @amazingrando to weigh in when they have time.

**Comment by amazingrando** [comment]
For the purposes of the CSV file itself, alphabetically by publisher, then alphabetically by product title, would make the list easy to parse.

For the Fate SRD the source order won't matter. I will process the data and sort it as needed.

**Comment by szabba** [comment]
Now then: do we want a pipeline that fails when a PR would mess up the CSV order?

**Comment by amazingrando** [comment]
@szabba I leave this decision to @johnhelmuth , if he wants to implement and support that.

**Comment by johnhelmuth** [comment]
If the order of the CSV doesn't affect the rendering of the Fate SRD website, then I don't personally have time to implement automation to keep it in order. (My saw sharpening time is going to other pursuits.)

@szabba  If you want to do a branch that implements that using Github actions, go ahead, I will continue the conversation and review and merge, etc.

**Comment by johnhelmuth** [comment]
I should have referenced this issue in the merge for PR#11 so it would auto close it.
